[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.typescript"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = [
  "echo 'TypeScript version:'",
  "npx tsc --version",
  "echo 'Node version:'",
  "node --version",
  "echo 'Skipping TypeScript type checking and compiling directly...'",
  "npx tsc --skipLibCheck --noEmit false"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=4096"
TS_NODE_TRANSPILE_ONLY = "true"