[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.typescript"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = [
  "echo 'TypeScript version:'",
  "npx tsc --version",
  "echo 'Node version:'",
  "node --version",
  "npm run build"
]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"
PORT = "8080"